### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by JonasV328** [jon-harper/E34M1#26]
I'm sorry if this is a stupid post.
Thank you for creating this thing. I'm thinking about building a Mercury Ony.1. Going through the documentation I had one question:
Why is this even needed? What did you have to change from the original EVA3 to make it compatible with Mercury One.1? Why could one not simply use the original EVA3? Is there a page where this is explained?

Thank you!

**Comment by jon-harper** [comment]
Quite a few things changed. 

The biggest issues was that Mercury One uses stacked belts, so that all four belt ends are in front of the X axis extrusion. EVA specifies that belts should go in front and behind the extrusion. Changing that led to other changes, such as reworking the entire back of EVA to remove the built-in belt tensioner.

After I got it working, I redesigned all of the parts to reduce weight, use the same heat set inserts that Mercury One uses, and so on. Hotends and extruder mounts are compatible with EVA 3, but otherwise it's a new toolhead.
